services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - path: .env
        required: false
    environment:
      CACHE_DIR: /app/data
    volumes:
      - ./data:/app/data
    restart: unless-stopped
